package com.skillboxhelloworld.module4

fun main() {
    println(Ammo.BulletPistol.damageDone())
    println(Ammo.BulletGun.damageDone())
    println(Ammo.BulletRifle.damageDone())

    println(FireType.SingleShot.shot(Ammo.BulletGun))
    println(FireType.TripleShot.shot(Ammo.BulletRifle))
    println(FireType.TripleShot.shot(Ammo.BulletPistol))

    var gun = Weapons.AWP()
//    println(gun.listAmmo)
    gun.takeBulletForShot()
//    println(gun.listAmmo)
    gun.takeBulletForShot()
//    println(gun.listAmmo)
    gun.takeBulletForShot()
//    println(gun.listAmmo)
//    gun.takeBulletForShot()
//    println(gun.listAmmo)
//    gun.takeBulletForShot()
//    println(gun.listAmmo)
//    gun.takeBulletForShot()
//    println(gun.listAmmo)
//    gun.takeBulletForShot()
//    println(gun.listAmmo)
//    gun.takeBulletForShot()
//    println(gun.listAmmo)
    var glock = Weapons.Glock()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    glock.takeBulletForShot()
    var ak = Weapons.AK()
    var famas = Weapons.Famas()
    famas.takeBulletForShot()
    famas.takeBulletForShot()
    ak.createBullet()

}